### ISSUE TITLE
Last example in README.md does not return values, just keys

### ISSUE THREAD

**Issue by DonPwrShellHunt** [StartAutomating/Irregular#115]
**Describe the bug**

The last example of PowerShell code in the README.md does not return values.

"number: 1
string: 'hello'" | ?<NewLine> -Split |  
    Foreach-Object {
        $key = $_ | ?<Colon> -Until -Trim -IncludeMatch
        $value = $key | ?<LineStartOrEnd> -Until -Trim
        @{$key.Trim(':')=$value}
    }

**To Reproduce**

1. Go to main code page on GitHub for Irregular
2. Scroll down to bottom of page
3. Click on icon to copy example code
4. Paste PowerShell code into PowerShell terminal window
5. Observe that the value content is missing

**Expected behavior**
I expect keys and values to be displayed.

**Actual behavior**
Name                           Value
----                           -----
number                         
string 

**Additional context**
This behavior was seen in both Windows PowerShell 5.1 and PowerShell 7.2.5

**Comment by StartAutomating** [comment]
@DonPwrShellHunt good catch!

Ironically, I just noticed this myself.  Thanks for saving me the issue creation.

**Comment by StartAutomating** [comment]
@DonPwrShellHunt 

Ok, the "fix" is to include the starting position of the match on the $value line:

~~~PowerShell
"number: 1
string: 'hello'" | ?<NewLine> -Split |  
    Foreach-Object {
        $key = $_ | ?<Colon> -Until -Trim -IncludeMatch
        $value = $key | ?<LineStartOrEnd> -Until -Trim -StartAt { $key.EndIndex }
        @{$key.Trim(':')=$value}
    }
~~~

The long story made short of "why" this issue occurred is that early versions of Irregular were more focused on string scanning.

Later versions are less inclined to do this automatically, because it makes piping inconvenient.

In the common case, it makes more sense have ```?<r1> | ?<r2>``` look for matches of r2 within matches of r1.
